version: '3'

services:
  api:
    image: flask-api
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    links:
      - db      
    depends_on:   
      - db
    ports:
      - "5000:5000"

  client:
    image: react-client
    build: 
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - .:/core
    ports:
      - '3000:3000'
    image: app:react
    container_name: react_container
    command: yarn start
 
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'mysql_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
        
    container_name: flask_mysql
