# syntax=docker/dockerfile:1

FROM python:3.9.7-slim-buster

WORKDIR ./backend

COPY backend/*.py backend/.env backend/requirements.txt ./

RUN pip install -r requirements.txt
ENV FLASK_APP main.py
ENV FLASK_ENV development

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "main:app"]