# syntax=docker/dockerfile:1

FROM python:3.9.7-slim-buster

WORKDIR ./backend

COPY * ./
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
RUN pip install -r requirements.txt
ENV FLASK_APP main.py
ENV FLASK_ENV development

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "main:app"]