version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    # command: ["flask", "run", "--host=0.0.0.0"]
    # volumes:
    #   - ./api:/backend
    # environment:
    #   - FLASK_ENV=development
    #   - FLASK_APP=app.py
    depends_on:
      - db
    ports:
      - "5000:5000"

  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    # volumes:
    #   - ./client:/frontend
    #   - node-modules:/frontend/node_modules
    # environment:
    #   - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - type: volume
        target: "/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cryptoexchange

# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile.api
#     image: flask-api
#     ports:
#       - "5000:5000"
#   client:
#     build:
#       context: .
#       dockerfile: Dockerfile.client
#     image: react-client
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - api
#     links:
#       - api
#   db:
#     image: postgres:13-alpine
#     volumes:
#       - type: volume
#         target: "/data"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=admin
#       - POSTGRES_DB=cryptoexchange
