version: "3"

services:
    flask_app:
        build: .
        restart: always
        ports:
            - "5000:5000"
        links:
            - db      
        depends_on:   
            - db
        container_name: flask_app


    db:
        image: mysql:latest
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'mysql_db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        
        container_name: flask_mysql
